# Generated by Django 6.0.8 on 2026-08-18 16:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='product_sku_idx',
            old_name='products_pr_sku_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_status_idx',
            old_name='products_pr_status_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_category_idx',
            old_name='products_pr_categor_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_created_idx',
            old_name='products_pr_created_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost price for internal tracking', max_digits=10, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='price'),
        ),
    ]
